### ISSUE TITLE
urlencode issue

### ISSUE THREAD

**Issue by Neo01010** [bit4woo/GUI_Burp_Extender_ReSign#2]
The request with url encoding will affect the signature result.

wrong signature:
![image](https://cloud.githubusercontent.com/assets/15312660/20613674/39c4d7d8-b301-11e6-8441-ff5e071e57b3.png)

right signature:
![image](https://cloud.githubusercontent.com/assets/15312660/20613667/2b77435a-b301-11e6-9810-0732fd2ff7a0.png)

**Comment by bit4woo** [comment]
the bug has been fixed in version 2.1. Please try.
