### ISSUE TITLE
burp插件问题

### ISSUE THREAD

**Issue by y9y2x8sz** [bit4woo/GUI_Burp_Extender_ReSign#6]
师傅你好:我看到你在这个代码中提到：https://github.com/bit4woo/ReSign/blob/master/src/burp/BurpExtender.java#L736
"当body是json格式的时候，这个方法也可以正常获取到键值对，牛掰。但是PARAM_JSON等格式不能通过updateParameter方法来更新"
当参数为static final byte PARAM_JSON = 6;的时候不能用updateParameter更新，请问需要用什么来更新请求，师傅有找到json更新的接口吗？想更改参数内容进行更新的时候报不支持这个方法”Action is not supported for this parameter type“
请师傅抽空回答下哈~谢谢，祝好。

**Comment by y9y2x8sz** [comment]
在https://github.com/bit4woo/burp-api-drops找着了

**Comment by robot183** [comment]
Json类型参数的值，不能用updateParameter更新，可以问下具体在哪里找到的解决方法么。
